# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c1c7fe9f49d0040d5a33c231623ba80730121fbe1dc6e9720a383ba011e7b2e13649acb0f8ddbb0b77b9f7f92a0eda786f777bafd3e83b94bfa8756cbfeb926

test:
  secret_key_base: beb6996431b0ccc99ecd723f757db495ccb47fac5cd57ec6b4bc659a9752ed84bf574d58dc608bf380ff2980d17a887747303acf3fed1ab1ee0ec3d96ad2099e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
